Repository vexide/pros-rs, pull requests merged in 2024-02, with the labels that each got.

#80 feat: feedforward controllers
  CHANGELOG.md
  TODO.md
  packages/pros/src/feedforward.rs
Labels: type:enhancement, semver:minor

#82 refactor(breaking): remove nonstandard printing macros
  CHANGELOG.md
  packages/pros/src/io/mod.rs
  packages/pros/src/io/print_impl.rs
  packages/pros/src/lib.rs
Labels: semver:major

#70 chore: add more lints
  CHANGELOG.md
  packages/pros/src/async_runtime/executor.rs
  packages/pros/src/async_runtime/reactor.rs
  packages/pros/src/competition.rs
  packages/pros/src/devices/adi/analog.rs
  packages/pros/src/devices/adi/digital.rs
  packages/pros/src/devices/adi/encoder.rs
  packages/pros/src/devices/adi/gyro.rs
  packages/pros/src/devices/adi/mod.rs
  packages/pros/src/devices/adi/motor.rs
  packages/pros/src/devices/adi/potentiometer.rs
  packages/pros/src/devices/adi/ultrasonic.rs
  packages/pros/src/devices/battery.rs
  packages/pros/src/devices/controller.rs
  packages/pros/src/devices/peripherals.rs
  packages/pros/src/devices/position.rs
  packages/pros/src/devices/smart/distance.rs
  packages/pros/src/devices/smart/gps.rs
  packages/pros/src/devices/smart/imu.rs
  packages/pros/src/devices/smart/link.rs
  packages/pros/src/devices/smart/mod.rs
  packages/pros/src/devices/smart/motor.rs
  packages/pros/src/devices/smart/optical.rs
  packages/pros/src/devices/smart/rotation.rs
  packages/pros/src/devices/smart/vision.rs
  packages/pros/src/error.rs
  packages/pros/src/io/print_impl.rs
  packages/pros/src/lcd/buttons.rs
  packages/pros/src/lcd/macros.rs
  packages/pros/src/lcd/mod.rs
  packages/pros/src/lib.rs
  packages/pros/src/lvgl/colors.rs
  packages/pros/src/pid.rs
  packages/pros/src/sync.rs
  packages/pros/src/task/local.rs
  packages/pros/src/task/mod.rs
  packages/pros/src/time.rs
  packages/pros/src/usd.rs
  packages/pros/src/vexos_env.rs
Labels: type:enhancement, semver:minor, type:refactor

#61 refactor: ADI devices
  CHANGELOG.md
  packages/pros/src/devices/adi/analog.rs
  packages/pros/src/devices/adi/digital.rs
  packages/pros/src/devices/adi/encoder.rs
  packages/pros/src/devices/adi/gyro.rs
  packages/pros/src/devices/adi/linetracker.rs
  packages/pros/src/devices/adi/mod.rs
  packages/pros/src/devices/adi/motor.rs
  packages/pros/src/devices/adi/potentiometer.rs
  packages/pros/src/devices/adi/solenoid.rs
  packages/pros/src/devices/adi/switch.rs
  packages/pros/src/devices/adi/ultrasonic.rs
  packages/pros/src/lib.rs
Labels: type:enhancement, semver:minor, scope:adi

#63 feat: ADI Expander
  CHANGELOG.md
  packages/pros/examples/adi_expander.rs
  packages/pros/src/devices/smart/expander.rs
  packages/pros/src/devices/smart/mod.rs
  packages/pros/src/lib.rs
Labels: type:enhancement, scope:smart_devices, semver:minor, scope:adi
