Repository vexide/pros-rs, pull requests merged in 2024-01, with the labels that each got.

#15 feat(controller): allow checking individual buttons/axis
  pros/src/controller.rs
Labels: enhancement

#16 feat(devices): V5 Inertial Sensor support
  TODO.md
  pros-sys/src/imu.rs
  pros/examples/imu.rs
  pros/src/lib.rs
  pros/src/sensors/imu.rs
  pros/src/sensors/mod.rs
Labels: bindings

#18 feat(devices): Optical sensor
  TODO.md
  pros-sys/src/lib.rs
  pros-sys/src/optical.rs
  pros/examples/optical.rs
  pros/src/lib.rs
  pros/src/sensors/mod.rs
  pros/src/sensors/optical.rs
Labels: bindings

#41 docs(feature-request): update grammar and heading levels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/small_issue.md
Labels: type:documentation, semver:patch

#36 fix(cargo): update config for wasm and remove runner
  .cargo/config.toml
Labels: type:bug, semver:patch

#40 feat(async-trait): switch to newly stabilized rust feature
  pros/Cargo.toml
  pros/examples/accessories.rs
  pros/examples/basic.rs
  pros/src/lib.rs
Labels: type:enhancement, scope:async_runtime, semver:major

#45 fix(imu): impl From instead of Into
  CHANGELOG.md
  pros/src/sensors/imu.rs
Labels: type:enhancement, scope:smart_devices, semver:minor

#30 feat(breaking): Terminal I/O
  CHANGELOG.md
  packages/pros/Cargo.toml
  packages/pros/examples/llemu.rs
  packages/pros/src/io.rs
  packages/pros/src/lcd/macros.rs
  packages/pros/src/lcd/mod.rs
  packages/pros/src/lib.rs
Labels: type:enhancement, scope:lcd, semver:major, scope:debugging

#38 refactor(breaking): Revised Competition API
  CHANGELOG.md
  packages/pros-sys/src/misc.rs
  packages/pros/src/competition.rs
Labels: type:enhancement, semver:minor

#37 chore: Fix tests + Examples, clarify docs
  .gitignore
  CHANGELOG.md
  packages/pros/Cargo.toml
  packages/pros/examples/imu.rs
  packages/pros/src/controller.rs
  packages/pros/src/error.rs
  packages/pros/src/lib.rs
  packages/pros/src/link.rs
  packages/pros/src/motor.rs
  packages/pros/src/pid.rs
  packages/pros/src/position.rs
  packages/pros/src/sensors/imu.rs
  packages/pros/src/sync.rs
  packages/pros/src/task/mod.rs
Labels: type:bug, type:documentation, type:enhancement, semver:patch

#55 feat(adi): ADI device bindings
  CHANGELOG.md
  packages/pros-sys/src/adi.rs
  packages/pros-sys/src/error.rs
  packages/pros/src/adi/analog.rs
  packages/pros/src/adi/digital.rs
  packages/pros/src/adi/encoder.rs
  packages/pros/src/adi/gyro.rs
  packages/pros/src/adi/mod.rs
  packages/pros/src/adi/motor.rs
  packages/pros/src/adi/port.rs
  packages/pros/src/adi/potentiometer.rs
  packages/pros/src/adi/ultrasonic.rs
Labels: semver:minor, scope:adi

#42 feat(task-local): add cell integration
  CHANGELOG.md
  packages/pros/src/task/local.rs
Labels: type:bug, type:enhancement, scope:rtos, semver:major

#34 refactor(breaking): Consistent API surface for devices
  CHANGELOG.md
  packages/pros/examples/accessories.rs
  packages/pros/examples/adi.rs
  packages/pros/examples/imu.rs
  packages/pros/examples/optical.rs
  packages/pros/src/adi/digital.rs
  packages/pros/src/adi/encoder.rs
  packages/pros/src/adi/gyro.rs
  packages/pros/src/adi/mod.rs
  packages/pros/src/adi/motor.rs
  packages/pros/src/adi/port.rs
  packages/pros/src/adi/potentiometer.rs
  packages/pros/src/adi/ultrasonic.rs
  packages/pros/src/devices/adi/analog.rs
  packages/pros/src/devices/adi/digital.rs
  packages/pros/src/devices/adi/encoder.rs
  packages/pros/src/devices/adi/gyro.rs
  packages/pros/src/devices/adi/mod.rs
  packages/pros/src/devices/adi/motor.rs
  packages/pros/src/devices/adi/potentiometer.rs
  packages/pros/src/devices/adi/ultrasonic.rs
  packages/pros/src/devices/battery.rs
  packages/pros/src/devices/controller.rs
  packages/pros/src/devices/mod.rs
  packages/pros/src/devices/position.rs
  packages/pros/src/devices/smart/distance.rs
  packages/pros/src/devices/smart/gps.rs
  packages/pros/src/devices/smart/imu.rs
  packages/pros/src/devices/smart/link.rs
  packages/pros/src/devices/smart/mod.rs
  packages/pros/src/devices/smart/motor.rs
  packages/pros/src/devices/smart/optical.rs
  packages/pros/src/devices/smart/rotation.rs
  packages/pros/src/devices/smart/vision.rs
  packages/pros/src/lib.rs
  packages/pros/src/sensors/mod.rs
Labels: type:enhancement, scope:smart_devices, semver:major

#53 feat(breaking): add `Peripherals` and `DynamicPeripherals` structs
  CHANGELOG.md
  packages/pros/examples/accessories.rs
  packages/pros/examples/adi.rs
  packages/pros/examples/dynamic_peripherals.rs
  packages/pros/examples/imu.rs
  packages/pros/examples/optical.rs
  packages/pros/src/devices/adi/mod.rs
  packages/pros/src/devices/mod.rs
  packages/pros/src/devices/peripherals.rs
  packages/pros/src/devices/smart/mod.rs
  packages/pros/src/lib.rs
Labels: scope:smart_devices, semver:major

#65 fix(breaking): imu_get_status error handling
  CHANGELOG.md
  packages/pros/src/devices/smart/imu.rs
Labels: type:bug, type:enhancement, scope:smart_devices, semver:major

#69 fix: resolve wasm build errors
  packages/pros-sys/src/lib.rs
  packages/pros/Cargo.toml
  packages/pros/src/io/mod.rs
  packages/pros/src/io/print_impl.rs
  packages/pros/src/lib.rs
Labels: type:bug, scope:platform_support, semver:major
